# Generated by Django 4.2.7 on 2023-11-13 10:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 13, 10, 7, 44, 864036, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("68dffda4-e4b5-458d-8490-6edefa5c29f3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
