# Generated by Django 4.2.7 on 2023-11-13 10:08

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_date_joined_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 13, 10, 8, 59, 81714, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("16b10548-1ad6-4c31-98c1-b38a687831ae"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
