# Generated by Django 4.2.7 on 2023-11-13 10:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_user_date_joined_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("852198da-a665-4d6a-b0bb-b8a52c0a6a5f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
