# Generated by Django 4.2.7 on 2023-11-13 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("923680d5-b14f-4758-a792-1132bd58bff3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="postattachment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9a89208b-87fe-4dc1-b02c-cfcabe5fdaea"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
