# Generated by Django 4.2.7 on 2023-11-13 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_post_id_alter_postattachment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0d2080f1-85ab-472e-9680-427ee28c651c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="postattachment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("fbf6d784-a588-4a68-afd9-e93ae4cf5a99"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
