# Generated by Django 4.2.7 on 2023-11-13 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_post_id_alter_postattachment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0037ab50-a40e-4d39-a653-15b231437b51"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="postattachment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
