# Generated by Django 4.2.7 on 2023-11-13 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_post_id_alter_postattachment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1fb993c5-263b-42ed-9448-4a33fb4f5ee9"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
